name = "SC Storm"
author = "BD103"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f4f6739bc46963e41cf44c7ba30f286c35cd6b952441756610f0ff07be55c145"

[versions]
forge = "40.1.74"
minecraft = "1.18.2"
