name = "SC Storm"
author = "BD103"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "33a7a4bb91b4cf1e97367aecec26abd993ddbd3498dae7511e52bf8f12cef0a1"

[versions]
forge = "40.0.0"
minecraft = "1.18.2"
